### ISSUE TITLE
Manager Account Error

### ISSUE THREAD

**Issue by captaincomando** [datkool/MuAccountManager#1]
all my configs ok database and mysql pass

for create account ok work fine
for manager account get error and no change any value #windows 10 x64 with framework 3.5 and 4.8

print

https://ibb.co/3FtrRHr

**Comment by datkool** [comment]
Are you run file .sql in folder tool?

Vào 05:30, T.6, 30 Th7, 2021 captaincomando ***@***.***> đã
viết:

**Comment by captaincomando** [comment]
my folder tool

https://ibb.co/8cmK4TM

**Comment by captaincomando** [comment]
my muaccountmanager i get forum is not complete
i download now your. all right work fine
but not is possible create char only account and edit account
ty great work. closed topic

**Comment by datkool** [comment]
I noticed you are missing characters.sql please check and run query from it
to use full functionality

Vào Th 6, 30 thg 7, 2021 vào lúc 20:59 captaincomando <
***@***.***> đã viết:
